### ISSUE TITLE
get/has/set string path only supports single character property names

### ISSUE THREAD

**Issue by andrewbridge** [cedmax/youmightnotneed#105]
Hi there,

Thanks for this repo, it's been useful to check myself before pulling in a fat library for utility functions.

I notice the get/has/set vanilla methods appear to only support single character properties:

```js
const testObj = { a: 1, b: { c: 2 }, foo: 3, d: { bar: 4 }, e: [undefined x 9, 'baz', 'buzz']  };

get(testObj, 'a'); // 1; CORRECT
get(testObj, 'b.c'); // 2; CORRECT
get(testObj, 'e[9]'); // 'baz'; CORRECT
get(testObj, 'foo'); // undefined; INCORRECT
get(testObj, 'd.bar'); // undefined; INCORRECT
get(testObj, 'e[10]'); // undefined; INCORRECT
```

I believe the fix is to add a greedy 1+ quantifier to the regex [(shown here in `get` but used in all three methods)](https://github.com/cedmax/youmightnotneed/blob/5ddc36caa7a13dc145113647cd0730afde66563a/src/content/lodash/object/get/vanilla.js#L5), i.e: `path.match(/([^[.\]]+)/g)`

This corrects the above cases, although it still doesn't cater for edge cases such as `'path.to["a key with a . [ or ] within it"]'`, though I'm unsure whether a single regex would be able to cater for such cases.

Happy to submit a PR myself when I get the time.

**Comment by cedmax** [comment]
Thanks for spotting this, I will try to have a look myself as well :)

**Comment by cedmax** [comment]
Update: I think it's literally a `+` missing in the regex, which means that also `has`, `set` and `unset` are broken in the same fashion, will do a PR tonight if you don't get there earlier, thank you again for raising the issue
