### ISSUE TITLE
Pick is incorrectly simplified, Lodash accepts path

### ISSUE THREAD

**Issue by alejandroiglesias** [cedmax/youmightnotneed#129]
The Lodash version of pick accepts a path, thus this is perfectly doable in Lodash:

```js
import { pick } from 'lodash'

const object = {
  a: 1,
  b: 2,
  c: { d: 3 },
}

pick(object, ['a', 'c.d'])
// => {a: 1, c: {d: 3}}
```
But there's no equivalent in ES6.

**Comment by cedmax** [comment]
Hi @alejandroiglesias, sorry for the late reply. 
Thanks for raising the issue, but this project was not meant to provide a drop in replacement for lodash: it's more meant to be a learning tool. The [get](https://youmightnotneed.com/lodash/#get) implementation shows how to achieve a similar behavior in case anyone wanted to pull things together, but I won't complicate the examples to do that as it would be beyond the point.
