### ISSUE TITLE
cross-js

### ISSUE THREAD

**Issue by jimmywarting** [cedmax/youmightnotneed#13]
Hello, I made a rule set of what you should think of when you are building cross Browser/Node.js applications, maybe you can come up with tips and help out?

https://github.com/cross-js/cross-js

**Comment by cedmax** [comment]
Hi @jimmywarting, sorry it took me a while to get at it, I can't fine the repo anymore though :(

**Comment by cedmax** [comment]
@jimmywarting I looked into it, but I'm not 100% sure I have the knowledge to help much, sorry: my expertise is mainly in the FE space, sorry
