### ISSUE TITLE
lodash get vanilla return default when falsy and not only when its undefined

### ISSUE THREAD

**Issue by webselect** [cedmax/youmightnotneed#139]
this code fix this
`const get = (obj, path, defaultValue) => {
  if (!path) return undefined;

  const pathArray = Array.isArray(path) ? path : path.match(/([^[.\]])+/g);
  let result = pathArray.reduce((acc, key) => acc && acc[key], obj);
  if (typeof result === 'undefined') {
    return defaultValue;
  }
  return result;
};
`

**Comment by cedmax** [comment]
Thanks @webselect for raising it and @102 for fixing it, I really appreciate (and sorry for the slow response on my side, it's been a busy couple of weeks 😓 )
