### ISSUE TITLE
Include file size information about lodash functions.

### ISSUE THREAD

**Issue by carcinocron** [cedmax/youmightnotneed#190]
Generally I think some lodash functions are necessary in pre-typescript code. But I was using `import find as 'lodash/find'` in a typescript project. While looking to prune my build size, I discovered that including `lodash/find` instead of using `array.find` actually cost me 5kb. Fair to say, 4.9kb of that was mostly magical stuff I wasn't using, but was very surprising.

I think including the estimated maximum savings, both disk and gzip'd variants with measured version number, would be useful information.

**Comment by carcinocron** [comment]
this website might be helpful: https://bundlephobia.com/package/lodash.find@4.6.0

**Comment by cedmax** [comment]
Hi @carcinocron, thanks for your contribution, but right at the moment this project is not meant to provide a drop in replacement for lodash: the idea is more to create an opportunity for people to learb more about javascript by looking at how certain lodash functionalities could be implemented in vanilla js.

Lodash covers way more edge cases and it's surely more resiliant when it comes to real world scenarios, especially when we go beyond the basic language built in methods (ie: filter, map, forEach, etc). 

I'm afraid that introducing any references to the bundle size, which is an incredibly important thing to have at heart, don't get me wrong, could suggest we recommend to drop lodash in favour of our simplified solutions, and that's not the right message.
