### ISSUE TITLE
You might not need regular expressions

### ISSUE THREAD

**Issue by MatrixFrog** [cedmax/youmightnotneed#21]
What do you think of adding a "you might not need RegExp" page? I occasionally see people using RegExp's when a simple `startsWith`, `endsWith` or `includes` would work perfectly well, would be more readable, and potentially be faster.

**Comment by cedmax** [comment]
If you have a few examples of how it might look like, I'd be more than happy to start working on it

**Comment by cedmax** [comment]
closed for inactivity
