### ISSUE TITLE
Moment - format - format simple test fails

### ISSUE THREAD

**Issue by codedbypaul** [cedmax/youmightnotneed#22]
Was looking into adding an object values example for lodash but found simple format test for moment is currently failing.

```
var date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
new Intl.DateTimeFormat('it-IT', {
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
}).format(date)
```

returns `"20/12/2012"` rather than `2012-12-20`

**Comment by cedmax** [comment]
interesting, not sure why this wasn't caught in the build or on my local. 
I'll look into it, thanks for the heads up

**Comment by cedmax** [comment]
@codedbypaul I don't get the same error on local or building on netlify, may I ask you your version of node and whether you installed the dependencies with yarn or npm?

**Comment by codedbypaul** [comment]
I'm using node 9.11.2 with yarn. If I run the same code in the Safari console I get the same result.

**Comment by cedmax** [comment]
sooo, I didn't manage to replicate the issue, could you do me a favour and try to run this test on your machine?

https://github.com/srl295/btest402

it's basically running [this file](https://raw.githubusercontent.com/srl295/btest402/master/btest402.js) in node to test the Intl support.
I'm sorry to put you through this but I can't think of anything else :(

**Comment by codedbypaul** [comment]
with 9.11.2 I get

`SUMMARY:Have Intl, Date:no 'tlh', Date:bad 'mt', Date:no 'ja',`

**Comment by cedmax** [comment]
exactly my result. I'm completely lost here, sorry.
Please feel free to open the PR with the test failing: as I said the build is going through and alas I don't have enough understanding of the problem (and time now, tbh) to investigate the issue properly :(

What I can tell is that in the browser (any browser) I get the same result you get, but in node it works.
I take away that probably the `Intl` is not the best option to achieve deterministic results.

**Comment by cedmax** [comment]
I decided to remove momentjs from the website in favour of an external resource.
Hence this is not relevant anymore
