### ISSUE TITLE
Debounce does not handle await promises well

### ISSUE THREAD

**Issue by sreeharsha-rav** [cedmax/youmightnotneed#228]
## Issue

Does not handle uncaught awaited promises well. https://github.com/cedmax/youmightnotneed/blob/production/src/content/lodash/function/debounce/vanilla.js

### Use case

using debounce for making asynchronous calls for a weather API.

### Problem 
Does not handle uncaught promises well:

Using debounce in `async fetchData` below:
<img width="252" alt="image" src="https://github.com/user-attachments/assets/1fa0a2e9-d2f4-47a1-b4e1-5ee6d7bf76b9">

Current debounce function ported from vanilla JS:
<img width="275" alt="image" src="https://github.com/user-attachments/assets/978426ef-458e-4520-8fb4-61c0f0dc4433">

## Suggested changes

Add an array of resolves to handle uncaught await promises.
<img width="272" alt="image" src="https://github.com/user-attachments/assets/aeb78528-b869-47a8-9725-7ad227db4f15">

Since above code is in typescript, equivalent code in js is:

```
export const debounce = (func, delay, { leading = false } = {}) => {
  let timerId = null;
  let resolveList = [];

  return (...args) => {
    if (!timerId && leading) {
      func(...args);
    }
    if (timerId) {
      clearTimeout(timerId);
    }

    return new Promise((resolve) => {
      resolveList.push(resolve);
      timerId = setTimeout(async () => {
        await func(...args);
        timerId = null;
        resolveList.forEach((res) => res());
        resolveList = [];
      }, delay);
    });
  };
};
```

**Comment by cedmax** [comment]
Hi @sreeharsha-rav, thanks for reaching out. 
I understand where you are coming from, but I don't think this is a change worth introducing in here: as much as the changes would make the implementation more robust, the point of this project is educational and not to create a drop in replacement for lodash.

The proposed changes complicate the script significantly, making it harder to read and, potentially, to understand.
I made a point of trying to keep the implementations as simple as possible, at the cost of some edge cases, and I think this one falls in that category.
