### ISSUE TITLE
Debounce with leading called twice on single invocation

### ISSUE THREAD

**Issue by Truffula** [cedmax/youmightnotneed#230]
If a debounced function with `leading: true` is called only once, the provided function is called twice on the first invocation. On subsequent invocations, it is only called once, after the timeout, since `timerId` isn't cleared.

**Comment by cedmax** [comment]
Would you care for creating a PR? since the nature of the project is NOT to create a drop in replacement for lodash (but to provide a learning space) I'd be leaning towards removing the `leading` option, to be honest

**Comment by 102** [comment]
#231 doesn't seem to complicate the existing solution too much, so it probably could be used

**Comment by cedmax** [comment]
thank you both 🙂
