### ISSUE TITLE
Make a "You might not need moment.js"

### ISSUE THREAD

**Issue by jimmywarting** [cedmax/youmightnotneed#3]
Getting tiered of ppl including the hole moment.js lib just to use it in a few places or only using a fraction of what moment.js provides. 

Yesterday i saw this on a nodejs backend

package.json
```
development: {
    moment: "1.something.x"
  }
```

And the only thing he did in the hole project was just this line of code: 
```js
moment(timestamp).format('YYYY-MM-DD')
```

-----

Things could have been replaced with just any of this:
```js
new Date(timestamp).toLocaleDateString()
new Date(timestamp).toLocaleDateString('sv-SE') // Will format yyyy-mm-dd
new Date(timestamp).toLocaleDateString('x-X') // unknown language will fallback to iso standard format (yyyy-mm-dd)
```

They need to learn that there is also [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)

**Comment by cedmax** [comment]
Right at the moment I don't have a "you might not need moment" section and the codebase is in a stack I don't particularly love (coffeescript + jade) as it's a quick fork from you might not need jquery without investing any time but collecting the lodash alternative scripts.

I want to keep this project alive and I will surely try to find some time to make it nicer for me to work with it and more extensible. 

I will surely keep this suggestion in mind :)

**Comment by cedmax** [comment]
I changed the structure quite a bit since you opened this issue @jimmywarting, if you want to help me with the `you might not need moment.js` this might be a good time :)

**Comment by jimmywarting** [comment]
I can help you come up with vanilla js solutions

**Comment by cedmax** [comment]
I will prepare a branch, hopefully tonight, thanks :)

**Comment by cedmax** [comment]
I opened the PR (https://github.com/cedmax/youmightnotneed/pull/10) with a couple initial formatting examples, feel free to open other PRs to that branch if you have any other valueable suggestion.
