### ISSUE TITLE
remove function does not match lodash 

### ISSUE THREAD

**Issue by x87** [cedmax/youmightnotneed#98]
Hey!

Thanks for your neat collection of plain JS functions. I have found something interesting while experimenting with a suggested replacement for lodash'es `remove`:

https://youmightnotneed.com/lodash/#remove
```
const remove = (array, iteratee) => 
  array.filter((item, i) => iteratee(item) && array.splice(i, 1))
```
This code mutates `array` as after each successful `iteratee`  which may negatively impact the final result if `iteratee` depends on `array`. Consider this example:

```
var arr = [1, 2, 3, 4, 5];
remove(arr, val => arr.length > 0)
```
the expected result for `remove` to return is `[1, 2, 3, 4, 5]` as `arr.length > 0` is truthy for all elements of `arr`. In reality it returns `[1, 3, 5]` and `arr` equals to `[2, 4]`.

`_.remove` returns `[1, 2, 3, 4, 5]` as expected.

**Comment by x87** [comment]
I ended up with the following function:

```
function removeFromArray(arr, iteratee) {
  const indexes = [];
  const removed = arr.filter((item, i) => iteratee(item) && indexes.push(i));

  for (let i = indexes.length - 1; i >= 0; i--) {
    arr.splice(indexes[i], 1);
  }
  return removed;
};
```

**Comment by cedmax** [comment]
Hi @x87, this is yet another reminder that this project might hardly be considered a proper drop in replacement for Lodash 😅
Thanks for pointing it out, I will have a look at adding some tests and sort the issue out
